version: "2"
services:
  postgres:
    build:
      context: services/postgres
      dockerfile: services/postgres/Dockerfile.development
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"

  client:
    build:
      context: services/app
      dockerfile: services/app/Dockerfile.development
    command: java -jar ./app.jar
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres:5432
      - JS_URL=http://localhost
    image: 'my-java-application'
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  db-data:
