version: "2"
services:
    users:
        image: maerodrim/clientlab
        expose:
            - 8080
        labels:
            project.git: "https://github.com/Maerodrim/Client_Lab.git"    # ссылка на репозиторий
            project.build: make                          # добавляем команду для сборки имидж
    db1:
      image: postgres:11.4
      restart: always
      environment:
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=postgres
           - POSTGRES_DB=mydb1
      ports:
           - "5434:5432"
      networks:
          - proxynet
